name: Build and Release Firmware

on:
    push:
        branches:
            - master # Adjust this branch name as needed

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  submodules: recursive
                  ref: ${{ github.event.inputs.branch || github.ref }}
                  path: qmk_firmware # Clone the repository under the name qmk_firmware

            - name: Install QMK
              run: |
                  sudo apt-get update -y
                  sudo apt-get install python3
                  sudo -H pip install qmk

            - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
              uses: carlosperate/arm-none-eabi-gcc-action@v1

            - name: Install Dependencies
              run: |
                  cd qmk_firmware
                  pip install -r requirements.txt

            - name: Build Firmware
              run: qmk compile -kb keychron/v1/iso_encoder -km frostplexx
              working-directory: qmk_firmware # Set the working directory to qmk_firmware

    release:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.sha }}
                  release_name: Firmware Release - ${{ github.sha }}
                  body: |
                      Release of the firmware for Keychron V1 ISO Keyboard.

            - name: Upload Firmware Artifact
              id: upload-release-asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./qmk_firmware/keychron_v1_iso_encoder_frostplexx.bin # Adjust this path as needed
                  asset_name: keychron_v1_iso_encoder_frostplexx_${{ steps.commit_sha.outputs.SHA }}.bin # Adjust the desired artifact name
                  asset_content_type: application/octet-stream
