name: Build and Release Firmware

on:
    push:
        branches:
            - master # Adjust this branch name as needed

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  submodules: recursive
                  ref: ${{ github.event.inputs.branch || github.ref }}
                  path: qmk_firmware # Clone the repository under the name qmk_firmware

            - name: Install QMK
              run: |
                  sudo apt-get update -y
                  sudo apt-get install python3
                  sudo -H pip install qmk
                  sudo apt-get install dfu-programmer

            - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
              uses: carlosperate/arm-none-eabi-gcc-action@v1

            - name: Install Dependencies
              run: |
                  cd qmk_firmware
                  pip install -r requirements.txt

            - name: Build Firmware
              run: qmk compile -kb keychron/v1/iso_encoder -km frostplexx
              working-directory: qmk_firmware # Set the working directory to qmk_firmware

            - name: Release Firmware
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  prerelease: false
                  files: |
                      *.bin
