name: Build and Release Firmware

on:
    push:
        branches:
            - master # Adjust this branch name as needed

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up QMK Environment
              run: |
                  sudo apt-get update -y
                  sudo apt-get install python3
                  sudo python3 -m pip install --user qmk

            - name: Build Firmware
              run: qmk compile -kb keychron/v1/iso_encoder -km frostplexx

    release:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.sha }}
                  release_name: Firmware Release - ${{ github.sha }}
                  body: |
                      Release of the firmware for Keychron V1 ISO Keyboard.

            - name: Upload Firmware Artifact
              id: upload-release-asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./keychron_v1_iso_encoder_frostplexx.bin # Adjust this path as needed
                  asset_name: keychron_v1_iso_encoder_frostplexx_${{ steps.commit_sha.outputs.SHA }}.bin # Adjust the desired artifact name
                  asset_content_type: application/octet-stream
